export const MODEL_FORMAT_VERSION = "1" as const;
export const LOW_CONFIDENCE_THRESHOLD = 0.7;
export const DEFAULT_REVIEW_CONFIDENCE_THRESHOLD = 0.95;
export const MAX_REVIEW_QUESTIONS = 10;
export const DEFAULT_SEARCH_MIN_SCORE = 0.35;
