export { DOCUMENT_MENTIONS_TABLE, DOCUMENT_ENTITIES_TABLE, DOCUMENT_FACTS_TABLE, ENTITY_PROFILES_TABLE, } from "./tables.js";
export const MENTION_CONTEXT_MAX_CHARS = 400;
export const MENTION_CONTEXT_LINE_RADIUS = 2;
export const ENTITY_MENTION_TYPE = "entity" as const;
