/**
 * @packageDocumentation
 * Anchor ontology contract: ontology spec, dataset provider interface, workspace layout,
 * review workflow, and model.yaml v1 serialization used by internal packages.
 */
/** Published npm package name. */
export const PACKAGE_NAME = "@trybacked/core" as const;
export {
  MODEL_FORMAT_VERSION,
  LOW_CONFIDENCE_THRESHOLD,
  DEFAULT_REVIEW_CONFIDENCE_THRESHOLD,
} from "./constants.js";
export {
  DOC_TYPE_TABLE_PREFIX,
  DOC_TYPE_UNKNOWN_SLUG,
  PIPELINE_INFRA_DATASET_TABLE_NAMES,
  PIPELINE_MATERIALIZED_DATASET_TABLE_NAMES,
  isDocumentTypeMaterializedTable,
  isPipelineInfraDatasetTable,
  createPipelineMaterializedDatasetTableSet,
} from "./tables.js";
export {
  NATIVE_FRACTIONAL_TYPE_PATTERN,
  PROFILE_TOP_VALUES_LIMIT,
  PROFILE_PATTERN_SAMPLE_SIZE,
  PROFILE_PATTERN_MATCH_THRESHOLD,
  PROFILE_FK_OVERLAP_THRESHOLD,
  PROFILE_FK_SAMPLE_SIZE,
  PROFILE_FK_CANDIDATES_PER_COLUMN,
  EMPTY_FOREIGN_KEY_CANDIDATES,
  ForeignKeyCandidateSchema,
  DetectedPatternKindSchema,
  DetectedPatternSchema,
  TopValueSchema,
  ColumnProfileSchema,
  TableProfileSchema,
  ProfileReportSchema,
} from "./profile.js";
export type {
  DetectedPatternKind,
  DetectedPattern,
  ForeignKeyCandidate,
  TopValue,
  ColumnProfile,
  TableProfile,
  ProfileReport,
} from "./profile.js";
export {
  ConfidenceSchema,
  ProvenanceSchema,
  SemanticTypeSchema,
  PropertyRoleSchema,
  ElementStatusSchema,
  PropertySchema,
  EntitySchema,
  CardinalitySchema,
  RelationSchema,
  RuleSchema,
  ModelMetadataSchema,
  SemanticModelSchema,
} from "./model.js";
export type {
  Confidence,
  Provenance,
  SemanticType,
  PropertyRole,
  ElementStatus,
  Property,
  Entity,
  Cardinality,
  Relation,
  Rule,
  ModelMetadata,
  SemanticModel,
} from "./model.js";
export {
  DoubtSchema,
  EvidenceTableSchema,
  ReviewQuestionKindSchema,
  ReviewQuestionSchema,
} from "./review-questions.js";
export type {
  Doubt,
  EvidenceTable,
  ReviewQuestionKind,
  ReviewQuestion,
} from "./review-questions.js";
export { ProposalUsageSchema, ProposalSchema } from "./proposal.js";
export type { ProposalUsage, Proposal } from "./proposal.js";
export {
  ReviewDecisionSchema,
  ReviewAnswerSchema,
  ReviewSchema,
  collectVerdicts,
  applyReview,
} from "./review.js";
export type {
  ReviewDecision,
  ReviewAnswer,
  Review,
  CollectVerdictsResult,
  ApplyReviewOptions,
  ApplyReviewResult,
} from "./review.js";
export { DiffChangeKindSchema, DiffChangeSchema, ModelDiffSchema } from "./diff.js";
export type { DiffChangeKind, DiffChange, ModelDiff } from "./diff.js";
export {
  BACKED_DIR_NAME,
  CONFIG_FILE_NAME,
  RUNS_DIR_NAME,
  MODEL_FILE_NAME,
  RUN_ARTIFACTS,
  DEFAULT_WORKSPACE_CONFIG,
  WorkspaceConfigSchema,
  workspacePaths,
  createRunId,
} from "./workspace.js";
export type { RunArtifactName, WorkspaceConfig, WorkspacePaths } from "./workspace.js";
export {
  writeWorkspaceConfig,
  patchWorkspaceConfig,
  readWorkspaceConfig,
} from "./workspace-config.js";
export { writeRunArtifact, readRunArtifact, hasRunArtifact, listRunIds } from "./run-artifacts.js";
export { serializeModelYaml, parseModelYaml, writeModelYaml, readModelYaml } from "./model-yaml.js";
export { ModelSearchMatchKindSchema, ModelSearchMatchSchema } from "./model-search-match.js";
export type { ModelSearchMatch } from "./model-search-match.js";
export {
  AUDIT_LOG_FILE_NAME,
  PUBLICATION_FILE_NAME,
  appendAuditEvents,
  auditLogPath,
  publicationPath,
  readAuditLog,
} from "./audit-log.js";
export {
  DatasetInspectionSchema,
  DatasetInspectionTableSchema,
  DiscoveryReportSchema,
  ONTOLOGY_FORMAT_VERSION,
  OntologyLifecycleStageSchema,
  AuditActionSchema,
  AuditActorSchema,
  AuditEventSchema,
  AuditLogSchema,
  EMPTY_AUDIT_LOG,
  applyReviewLifecycle,
  buildAutoConfirmAuditEvents,
  buildPublishAuditEvent,
  buildRollbackAuditEvent,
  buildReviewAuditEvents,
  diffOntology,
  formatOntologyDiff,
  hasBreakingOntologyChanges,
  OntologyDiffChangeKindSchema,
  OntologyDiffChangeSchema,
  OntologyDiffSchema,
  canAdvanceLifecycle,
  isGovernedLifecycleStage,
  lifecycleFromModelStatus,
  lifecycleStageIndex,
  markOntologyPublished,
  mergeAuditLogs,
  GovernanceElementKindSchema,
  OntologyGovernanceError,
  OntologyGovernancePatchSchema,
  applyOntologyGovernancePatch,
  buildGovernanceAuditEvent,
  isGovernancePatchAction,
  OntologyActionHandlerSchema,
  OntologyActionInputSchema,
  OntologyActionSchema,
  OntologyLogicSchema,
  OntologyMetadataSchema,
  OntologyObjectSchema,
  OntologyPropertyRoleSchema,
  OntologyPropertySchema,
  OntologyPropertyTypeSchema,
  OntologyProvenanceSchema,
  OntologyRelationshipCardinalitySchema,
  OntologyRelationshipSchema,
  OntologySchema,
  mergeValidationResults,
  semanticModelToOntology,
  validateOntology,
  validateSemanticModel,
  validationResult,
} from "./ontology/index.js";
export type {
  AuditAction,
  AuditActor,
  AuditEvent,
  AuditLog,
  DatasetInspection,
  DatasetInspectionTable,
  DiscoveryReport,
  OntologyLifecycleStage,
  OntologyDiff,
  OntologyDiffChange,
  OntologyDiffChangeKind,
  ApplyReviewLifecycleOptions,
  ReviewLifecycleResult,
  GovernanceElementKind,
  GovernancePatchAction,
  OntologyGovernancePatch,
  Dataset,
  DatasetColumn,
  DatasetColumnStatistics,
  DatasetIdentifier,
  DatasetMetadata,
  DatasetProvider,
  DatasetSample,
  DatasetSchema,
  DatasetStatistics,
  Ontology,
  OntologyAction,
  OntologyLogic,
  OntologyMetadata,
  OntologyObject,
  OntologyProperty,
  OntologyPropertyRole,
  OntologyPropertyType,
  OntologyProvenance,
  OntologyRelationship,
  OntologyRelationshipCardinality,
  SampleOptions,
  ValidationIssue,
  ValidationResult,
  ValidationSeverity,
} from "./ontology/index.js";
