#!/usr/bin/env python3
"""Generate fixed ASCII logo art from docs/assets/logo-white.png → apps/cli/src/ui/logo-art.ts"""

from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/assets/logo-white.png"
TARGET = ROOT / "apps/cli/src/ui/logo-art.ts"

TARGET_WIDTH = 100
CHAR_ASPECT = 0.48
ALPHA_MIN = 80
LUMINANCE_MIN = 100
GLYPH = "#"


def is_glyph_pixel(r: int, g: int, b: int, a: int) -> bool:
    if a < ALPHA_MIN:
        return False
    return (r + g + b) / 3 > LUMINANCE_MIN


def convert_logo() -> list[str]:
    img = Image.open(SOURCE).convert("RGBA")
    alpha = img.split()[3]
    bbox = alpha.point(lambda value: 255 if value > 32 else 0).getbbox()
    if bbox is None:
        raise SystemExit(f"No visible content in {SOURCE}")
    img = img.crop(bbox)

    target_height = max(7, int(img.height / img.width * TARGET_WIDTH * CHAR_ASPECT))
    resized = img.resize((TARGET_WIDTH, target_height), Image.Resampling.LANCZOS)

    lines: list[str] = []
    for y in range(target_height):
        row = []
        for x in range(TARGET_WIDTH):
            red, green, blue, opacity = resized.getpixel((x, y))
            row.append(GLYPH if is_glyph_pixel(red, green, blue, opacity) else " ")
        line = "".join(row).rstrip()
        if line.strip():
            lines.append(line)

    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()

    return lines


def emit_typescript(lines: list[str]) -> str:
    body = "\n".join(f'  "{line}",' for line in lines)
    return f"""/** AUTO-GENERATED by scripts/generate-logo-art.py — do not edit by hand. */

export const LOGO_ART_LINES = [
{body}
] as const;
"""


def main() -> None:
    lines = convert_logo()
    TARGET.write_text(emit_typescript(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(lines)} lines to {TARGET}")


if __name__ == "__main__":
    main()
