export {
  createBackedClient,
  AnchorApiError,
  type BackedClient,
  type BackedClientOptions,
  type GatewayBackedClient,
  type GatewayBackedClientOptions,
  type PlatformBackedClient,
  type PlatformBackedClientOptions,
  type TenantClient,
} from "./client.js";
export type { AuthModule, HealthModule } from "./modules/auth.js";
export type { TransportOptions } from "./transport.js";

export type {
  GatewayAuthMode,
  GatewayHealth,
  GatewaySession,
  LoginRequest,
  LoginResponse,
  LogoutResponse,
} from "@trybacked/core";

export type {
  ChunkSearchBody,
  ChunkSearchResponse,
  DefinitionResult,
  DocumentPreviewResponse,
  DocumentProvenance,
  EntityDetail,
  EntityProfileBody,
  EntityProfileResponse,
  EntityProvenance,
  EntitySearchBody,
  EntitySearchResponse,
  EntitySummary,
  FileEntry,
  GetDefinitionResponse,
  GetDocumentResponse,
  GetEntityResponse,
  GraphTraverseBody,
  GraphTraverseResponse,
  HealthResponse,
  ListEntitiesResponse,
  ListFilesResponse,
  ListRelationsResponse,
  ObjectQueryBody,
  ObjectQueryResponse,
  RefreshRun,
  RefreshRunStatus,
  RelationSummary,
  RowProvenance,
  SearchMatch,
  SemanticAskResponse,
  SemanticAskResult,
  SemanticAskStep,
  UploadedFile,
} from "@trybacked/service";
