import { publishTenantDocumentOntologyToVolume } from "@trybacked/platform-admin";
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { executeAdminSql, runDatabricksCliOrThrow } from "./databricks-cli.js";
import { ensureRegistryVolume, grantPlatformPrincipalOnTenant } from "./platform-grants.js";
import {
  ensureTenantInRegistry,
  loadTenantsRegistry,
  resolveBundleTarget,
  resolveTenantCatalog,
  saveTenantsRegistry,
  type TenantsRegistry,
} from "./registry.js";
import { databricksConfigFromEnrollment } from "./remote-ontology.js";
import { findBackedRepoRoot } from "./repo-root.js";
import { createOboToken, ensureServicePrincipal } from "./service-principal.js";
export type TenantCreateOptions = {
  tenantId: string;
  sharedSpaceKeys: string[];
  dryRun: boolean;
  skipBundle: boolean;
  repoRoot?: string | undefined;
};
export type TenantCreateResult = {
  tenantId: string;
  catalog: string;
  envFile: string;
  bundleTarget: string;
  servicePrincipalAppId: string;
  registryUpdated: boolean;
  publicationVersion: number;
};
function normalizeHost(hostUrl: string): string {
  return hostUrl.replace(/^https?:\/\//, "").replace(/\/+$/, "");
}
function enrollmentHostUrl(registry: TenantsRegistry): string {
  const host = registry.enrollment.host;
  return host.startsWith("http") ? host : `https://${host}`;
}
function writeTenantTargetFile(
  repoRoot: string,
  target: string,
  hostUrl: string,
  catalog: string,
): void {
  const targetsDir = join(repoRoot, "pipeline", "targets");
  mkdirSync(targetsDir, { recursive: true });
  const targetPath = join(targetsDir, `${target}.yml`);
  const body = `# Tenant target — generated by backed tenant create.
targets:
  ${target}:
    workspace:
      host: ${hostUrl}
      root_path: /Workspace/Shared/.bundle/backed-pipeline/${target}
    variables:
      catalog: ${catalog}
`;
  writeFileSync(targetPath, body, "utf8");
}
function readExistingToken(envFile: string): string | undefined {
  if (!existsSync(envFile)) {
    return undefined;
  }
  const line = readFileSync(envFile, "utf8")
    .split("\n")
    .find((entry) => entry.startsWith("BACKED_DATABRICKS_TOKEN="));
  if (line === undefined) {
    return undefined;
  }
  const token = line.slice("BACKED_DATABRICKS_TOKEN=".length).trim();
  return token.length > 0 ? token : undefined;
}
function writeTenantEnvFile(options: {
  envFile: string;
  host: string;
  token: string;
  warehouseId: string;
  catalog: string;
}): void {
  mkdirSync(dirname(options.envFile), { recursive: true });
  const body = [
    `BACKED_DATABRICKS_HOST=${options.host}`,
    `BACKED_DATABRICKS_TOKEN=${options.token}`,
    `BACKED_DATABRICKS_WAREHOUSE_ID=${options.warehouseId}`,
    `BACKED_DATABRICKS_CATALOG=${options.catalog}`,
    "BACKED_DATABRICKS_SCHEMA=docs",
    "",
  ].join("\n");
  writeFileSync(options.envFile, body, "utf8");
  chmodEnvFileBestEffort(options.envFile);
}
function chmodEnvFileBestEffort(path: string): void {
  try {
    chmodSync(path, 0o600);
  } catch {
    return;
  }
}
function grantSharedSpaces(
  profile: string,
  warehouseId: string,
  registry: TenantsRegistry,
  catalog: string,
  applicationId: string,
  sharedKeys: string[],
): Promise<void>[] {
  const tasks: Promise<void>[] = [
    executeAdminSql({
      profile,
      warehouseId,
      statement: `GRANT ALL PRIVILEGES ON CATALOG \`${catalog}\` TO \`${applicationId}\``,
    }),
  ];
  for (const key of sharedKeys) {
    const space = registry.shared_spaces[key];
    if (space === undefined) {
      throw new Error(`Unknown shared space "${key}" in tenants.yaml shared_spaces.`);
    }
    if (space.catalog === catalog) {
      continue;
    }
    tasks.push(
      executeAdminSql({
        profile,
        warehouseId,
        statement: `GRANT USE CATALOG ON CATALOG \`${space.catalog}\` TO \`${applicationId}\``,
      }),
      executeAdminSql({
        profile,
        warehouseId,
        statement: `GRANT USE SCHEMA ON SCHEMA \`${space.catalog}\`.\`${space.schema}\` TO \`${applicationId}\``,
      }),
      executeAdminSql({
        profile,
        warehouseId,
        statement: `GRANT SELECT ON SCHEMA \`${space.catalog}\`.\`${space.schema}\` TO \`${applicationId}\``,
      }),
    );
  }
  return tasks;
}
export async function provisionTenant(options: TenantCreateOptions): Promise<TenantCreateResult> {
  const repoRoot = options.repoRoot ?? findBackedRepoRoot();
  const registryPath = join(repoRoot, "tenants.yaml");
  const registry = loadTenantsRegistry(registryPath);
  const profile = registry.enrollment.profile;
  const warehouseId = registry.enrollment.warehouse_id;
  const catalog = resolveTenantCatalog(options.tenantId);
  const bundleTarget = resolveBundleTarget(options.tenantId, registry.enrollment.bundle_target);
  const hostUrl = enrollmentHostUrl(registry);
  const host = normalizeHost(hostUrl);
  const spName = `backed-tenant-${options.tenantId}`;
  const envFile = join(process.env["HOME"] ?? "", ".config", "backed", `${options.tenantId}.env`);
  if (options.dryRun) {
    return {
      tenantId: options.tenantId,
      catalog,
      envFile,
      bundleTarget,
      servicePrincipalAppId: "(dry-run)",
      registryUpdated: false,
      publicationVersion: 0,
    };
  }
  await executeAdminSql({
    profile,
    warehouseId,
    statement: `CREATE CATALOG IF NOT EXISTS \`${catalog}\` COMMENT 'Backed tenant: ${options.tenantId}'`,
  });
  await ensureRegistryVolume(profile, warehouseId, catalog);
  if (options.tenantId !== "backed") {
    writeTenantTargetFile(repoRoot, bundleTarget, hostUrl, catalog);
  }
  if (!options.skipBundle) {
    runDatabricksCliOrThrow(["bundle", "deploy", "-t", bundleTarget, "--auto-approve"], {
      profile,
      cwd: join(repoRoot, "pipeline"),
      label: "bundle deploy",
    });
  }
  const { applicationId } = ensureServicePrincipal(profile, spName);
  let token = readExistingToken(envFile);
  if (token === undefined) {
    token = createOboToken(profile, applicationId, options.tenantId);
  }
  await Promise.all(
    grantSharedSpaces(
      profile,
      warehouseId,
      registry,
      catalog,
      applicationId,
      options.sharedSpaceKeys,
    ),
  );
  const platformPrincipal = registry.enrollment.platform_principal;
  if (platformPrincipal !== undefined && platformPrincipal.length > 0) {
    await grantPlatformPrincipalOnTenant({
      profile,
      warehouseId,
      registry,
      catalog,
      platformPrincipal,
      sharedKeys: options.sharedSpaceKeys,
    });
  }
  runDatabricksCliOrThrow(
    [
      "api",
      "patch",
      `/api/2.0/permissions/sql/warehouses/${warehouseId}`,
      "--json",
      JSON.stringify({
        access_control_list: [
          { service_principal_name: applicationId, permission_level: "CAN_USE" },
        ],
      }),
    ],
    { profile, label: "warehouse CAN_USE" },
  );
  writeTenantEnvFile({ envFile, host, token, warehouseId, catalog });
  const { version: publicationVersion } = await publishTenantDocumentOntologyToVolume({
    tenantId: options.tenantId,
    catalog,
    adminConfig: databricksConfigFromEnrollment(registry),
  });
  const hadTenant = registry.tenants[options.tenantId] !== undefined;
  const updated = ensureTenantInRegistry(registry, options.tenantId, options.sharedSpaceKeys);
  if (!hadTenant) {
    saveTenantsRegistry(registryPath, updated);
  }
  return {
    tenantId: options.tenantId,
    catalog,
    envFile,
    bundleTarget,
    servicePrincipalAppId: applicationId,
    registryUpdated: !hadTenant,
    publicationVersion,
  };
}
